version: '3'
services:
  sshd:
    build: ./
    ports:
      - "2222:22"
    volumes:
      - ./data:/data
    restart: unless-stopped

networks:
  default:
    external:
      name: ${NETWORK:-sshd}
