version: '3'
services:
  sshd:
    build: .
    image: alpine-sshd
    container_name: sshd
    ports:
      - "2222:22"
    volumes:
      - ./data/sshd:/data:rw
      - shared-volume:/var/log
    restart: unless-stopped

  fail2ban:
    image: crazymax/fail2ban
    container_name: fail2ban
    network_mode: "host"
    cap_add:
      - NET_ADMIN
      - NET_RAW
    volumes:
      - "./data/fail2ban:/data"
      - shared-volume:/var/log
    env_file:
      - ./fail2ban.env
    restart: always

volumes:
  shared-volume:

networks:
  default:
    external:
      name: ${NETWORK:-sshd}
