version: '3'
services:
  sshd:
    container_name: sshd
    build: ./
    image: alpine-sshd
    ports:
      - "2222:22"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./log:/var/log:rw
      - ./data:/data:rw
    restart: unless-stopped

networks:
  default:
    external:
      name: ${NETWORK:-sshd}
